required: sudo
services:
  - docker

before_install:
  - docker build -t muyioden/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run muyioden/react-test npm test -- --coverage

after_success:
  - docker build -t muyidocker/multi-client ./client
  - docker build -t muyidocker/multi-nginx ./nginx
  - docker build -t muyidocker/multi-server ./server
  - docker build -t muyidocker/multi-worker ./worker

# Docker login before pushing build to docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# Push build to docker hub
  - docker push muyidocker/multi-client
  - docker push muyidocker/multi-nginx
  - docker push muyidocker/multi-server
  - docker push muyidocker/multi-worker

deploy:
  provider: elasticbeanstalk 
  region: us-west-2
  app: multi-docker-cn
  env: MultiDockerCn-env
  bucket_name: /elasticbeanstalk-us-west-2-139985006656
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY